# Differences Between `np.array` and `np.matrix`

In [1]:
import numpy as np

## Prepare some matrices

In [2]:
A = [[1, 2], [3, 4]]

B = [[0.5], [1.5]]

In [3]:
A_m = np.matrix(A)   # numpy.matrix object
A_m

matrix([[1, 2],
        [3, 4]])

In [4]:
A_a = np.array(A)   # numpy.ndarray object
A_a

array([[1, 2],
       [3, 4]])

In [5]:
(A_a == A_m)  # Note, returns np.matrix

matrix([[ True,  True],
        [ True,  True]])

<font color='red'>**DIFFERENCE:**</font>

In [6]:
# Alterantive constructor from matlab-like string literal
np.matrix("[1 2; 3 4]")

matrix([[1, 2],
        [3, 4]])

In [7]:
B_m = np.matrix(B)
B_m

matrix([[0.5],
        [1.5]])

In [8]:
B_a = np.array(B)
B_a

array([[0.5],
       [1.5]])

In [9]:
(B_m == B_a)

matrix([[ True],
        [ True]])

## Transpose

In [10]:
A_m.T

matrix([[1, 3],
        [2, 4]])

In [11]:
A_m.transpose()

matrix([[1, 3],
        [2, 4]])

In [12]:
A_a.T

array([[1, 3],
       [2, 4]])

In [13]:
A_a.transpose()

array([[1, 3],
       [2, 4]])

In [14]:
B_m.T == B_a.T

matrix([[ True,  True]])

## <font color='red'>DIFFERENCE:</font> Matrix multiplication

In [15]:
A_m*B_m  # Matrix multiplication

matrix([[3.5],
        [7.5]])

In [16]:
np.multiply(A_m, B_m)  # Element-wise multiplication with broadcasting

matrix([[0.5, 1. ],
        [4.5, 6. ]])

In [17]:
np.matmul(A_a, B_a)  # Matrix multiplication (preferred over A_a.dot(B_a))

array([[3.5],
       [7.5]])

In [18]:
A_a*B_a  # Element-wise multiplication with broadcasting

array([[0.5, 1. ],
       [4.5, 6. ]])

In [19]:
A_a@B_a  # Matrix multiplication - Python 3.5+ only

array([[3.5],
       [7.5]])

In [20]:
np.mat(A)*np.mat(B_a)  # Matrix multiplication - alternative

matrix([[3.5],
        [7.5]])

In [21]:
A_m@B_m  # Just checking...

matrix([[3.5],
        [7.5]])

In [22]:
B_a*B_a  # Element-wise multiplication

array([[0.25],
       [2.25]])

In [23]:
try:
    B_m*B_m
except ValueError as err:
    print(err)

shapes (2,1) and (2,1) not aligned: 1 (dim 1) != 2 (dim 0)


In [24]:
B_m.T*B_m  # Matrix multiplication

matrix([[2.5]])

In [25]:
B_a.T*B_a  # Element-wise multiplication with broadcasting

array([[0.25, 0.75],
       [0.75, 2.25]])

In [26]:
np.matmul(B_a.T, B_a)  # Matrix multiplication

array([[2.5]])

In [27]:
B_a.T@B_a  # Matrix multiplication

array([[2.5]])

### Performance tests

In [28]:
n = 10  # Not very big
Big_a = np.random.randn(n, n)
Big_m = np.matrix(Big_a)

assert (Big_m*(Big_m/2) == Big_a@(Big_a/2)).all()

In [29]:
%timeit np.matmul(Big_a, Big_a/2)

3.85 µs ± 26.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [30]:
%timeit Big_a@(Big_a/2)

3.74 µs ± 23.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [31]:
%timeit Big_m*(Big_m/2)

11.1 µs ± 30.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [32]:
%timeit np.mat(Big_a)*np.mat(Big_a/2)

17.8 µs ± 35.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [33]:
n = 1000  # Big
Big_a = np.random.randn(n, n)
Big_m = np.matrix(Big_a)

assert (Big_m*(Big_m/2) == Big_a@(Big_a/2)).all()

In [34]:
%timeit np.matmul(Big_a, (Big_a/2))

22.4 ms ± 538 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [35]:
%timeit Big_a@(Big_a/2)

23.3 ms ± 780 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [36]:
%timeit Big_m*(Big_m/2)

25.2 ms ± 883 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [37]:
%timeit np.mat(Big_a)*np.mat(Big_a/2)

24.6 ms ± 1.05 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Other operations

In [38]:
A_m*3  # Scalar multiplication (element-wise)

matrix([[ 3,  6],
        [ 9, 12]])

In [39]:
A_m/3 == A_a/3  # Scalar division (element-wise)

matrix([[ True,  True],
        [ True,  True]])

In [40]:
3/A_m  # Scalar division

matrix([[3.  , 1.5 ],
        [1.  , 0.75]])

In [41]:
3/A_a  # Scalar division

array([[3.  , 1.5 ],
       [1.  , 0.75]])

In [42]:
A_a + B_a  # Addition with broadcasting

array([[1.5, 2.5],
       [4.5, 5.5]])

In [43]:
A_m + B_m  # Addition with broadcasting

matrix([[1.5, 2.5],
        [4.5, 5.5]])

In [44]:
np.sqrt(A_m)  # Ufuncs work element-wise

matrix([[1.        , 1.41421356],
        [1.73205081, 2.        ]])

In [45]:
np.sqrt(A_a)  # Ufuncs work element-wise

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [46]:
np.hstack([A_m, B_m])  # Concatenating

matrix([[1. , 2. , 0.5],
        [3. , 4. , 1.5]])

In [47]:
np.hstack([A_a, B_a])  # Concatenating

array([[1. , 2. , 0.5],
       [3. , 4. , 1.5]])

## <font color='red'>DIFFERENCE:</font> Matrix exponents

In [48]:
A_m**2

matrix([[ 7, 10],
        [15, 22]])

In [49]:
A_a**2  # Element-wise powers

array([[ 1,  4],
       [ 9, 16]])

In [50]:
np.linalg.matrix_power(A_a, 2)  # Matrix exponents

array([[ 7, 10],
       [15, 22]])

In [51]:
np.linalg.matrix_power(A_m, 2) == np.linalg.matrix_power(A_a, 2)

matrix([[ True,  True],
        [ True,  True]])

## Indexing

In [52]:
x = A_m[0, 1]
x

2

In [53]:
x = A_a[0, 1]
x

2

<font color='red'>**DIFFERENCE:**</font> 

In [54]:
# Now the problems start...

c_m = A_m[1]
c_m

matrix([[3, 4]])

In [55]:
c_m.shape

(1, 2)

In [56]:
c_a = A_a[1]
c_a

array([3, 4])

In [57]:
c_a.shape  # Lost a dimension !!!

(2,)

In [58]:
c_a = A_a[1].reshape(1, -1)  # Preserves dimension
c_a

array([[3, 4]])

## Slicing

In [59]:
c_m = A_m[0:1]
c_m.shape

(1, 2)

In [60]:
c_a = A_a[0:1]  # Dimension stays the same
c_a.shape

(1, 2)

In [61]:
A_m[1:2, 1:2]

matrix([[4]])

In [62]:
A_a[1:2, 1:2]  # Dimension stays the same

array([[4]])

In [63]:
A_m[(0, 0, 1, 1), (0, 1, 0, 1)]  # Still 2-dimensional

matrix([[1, 2, 3, 4]])

In [64]:
A_a[(0, 0, 1, 1), (0, 1, 0, 1)]  # Lost a dimension

array([1, 2, 3, 4])

## Basic linear algebra

In [65]:
np.linalg.norm(B_m) == np.linalg.norm(B_a)

True

In [66]:
A_m.I

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [67]:
np.linalg.inv(A_a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [68]:
np.linalg.inv(A_m) == np.linalg.inv(A_a)

matrix([[ True,  True],
        [ True,  True]])