In [1]:
# First let's remember what lists can do!

mylist = [[1, 2], [3, 4], [5, 6]]

In [2]:
mylist

[[1, 2], [3, 4], [5, 6]]

In [3]:
mylist[0]

[1, 2]

In [4]:
mylist[0][0]

1

In [5]:
mylist[0][1]

2

In [6]:
mylist[2][1]

6

In [7]:
len(mylist)

3

In [8]:
import numpy as np

In [9]:
a = np.array(mylist)

In [10]:
type(a)

numpy.ndarray

In [11]:
# 'ndarray' stands for n-dimensional array

In [12]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
a.shape

(3, 2)

In [14]:
a[0,0]

1

In [15]:
a[0,1]

2

In [16]:
# cool!

In [17]:
a*2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [18]:
a - 1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [19]:
a*a

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [20]:
b = np.zeros(12)

In [21]:
b

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [22]:
b.resize((3,4))

In [23]:
b

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [24]:
c = np.random.rand(12)

In [25]:
c

array([ 0.39647949,  0.11706946,  0.12829639,  0.97434799,  0.84878815,
        0.56709941,  0.03616665,  0.5487622 ,  0.17135464,  0.33234549,
        0.39441865,  0.79183875])

In [26]:
c.resize((3,4))

In [27]:
c

array([[ 0.39647949,  0.11706946,  0.12829639,  0.97434799],
       [ 0.84878815,  0.56709941,  0.03616665,  0.5487622 ],
       [ 0.17135464,  0.33234549,  0.39441865,  0.79183875]])

In [28]:
b*c

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [29]:
d = np.ones((3,4))

In [30]:
d

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [31]:
d = d * 10
d

array([[ 10.,  10.,  10.,  10.],
       [ 10.,  10.,  10.,  10.],
       [ 10.,  10.,  10.,  10.]])

In [32]:
d*c

array([[ 3.96479486,  1.17069458,  1.28296387,  9.74347994],
       [ 8.48788148,  5.67099413,  0.36166649,  5.487622  ],
       [ 1.71354643,  3.3234549 ,  3.9441865 ,  7.91838754]])

In [33]:
d.dtype

dtype('float64')

In [34]:
e = np.array(range(12), dtype=int).reshape(3,4)

In [35]:
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
sum(e)

array([12, 15, 18, 21])

In [37]:
np.sum(e)

66

In [38]:
np.sum(e, axis=0)

array([12, 15, 18, 21])

In [39]:
np.sum(e, axis=1)

array([ 6, 22, 38])

In [40]:
def f(x):
    return x**2 - 5

In [41]:
f(4)

11

In [42]:
# Numpy arrays work with your functions!
f(e)

array([[ -5,  -4,  -1,   4],
       [ 11,  20,  31,  44],
       [ 59,  76,  95, 116]])

In [43]:
# Transpose matrix
e.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [44]:
d

array([[ 10.,  10.,  10.,  10.],
       [ 10.,  10.,  10.,  10.],
       [ 10.,  10.,  10.,  10.]])

In [45]:
# Matrix multiplication
d.dot()

TypeError: Required argument 'b' (pos 1) not found

In [46]:
e.dot(d.T)

array([[  60.,   60.,   60.],
       [ 220.,  220.,  220.],
       [ 380.,  380.,  380.]])

In [47]:
# save to disk as a text file
np.savetxt("test.txt", e)

In [48]:
# load from textfile
f = np.loadtxt("test.txt")

In [49]:
f

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [50]:
f = open("test.txt")
print f.read()

0.000000000000000000e+00 1.000000000000000000e+00 2.000000000000000000e+00 3.000000000000000000e+00
4.000000000000000000e+00 5.000000000000000000e+00 6.000000000000000000e+00 7.000000000000000000e+00
8.000000000000000000e+00 9.000000000000000000e+00 1.000000000000000000e+01 1.100000000000000000e+01



In [51]:
# Random numbers - normally distributed
e = np.random.randn(10000).reshape(100, 100)

In [52]:
e.shape

(100, 100)

In [53]:
# Save as a binary file
np.save("test", e)

In [54]:
import os
statinfo = os.stat('test.npy')
print statinfo.st_size

80080


In [55]:
f = np.load("test.npy")

In [56]:
f.shape

(100, 100)

In [57]:
np.mean(f)

0.017397329861261787

In [58]:
np.max(f)

4.0840898625130562

In [59]:
np.min(f)

-3.7300638100213588

In [60]:
# Standard deviation
np.std(f)

1.0050085017460315

In [61]:
# Many other modules use numpy arrays
from scipy import misc

In [62]:
# Load image from image file
image = misc.imread('pi_image.jpg')

In [63]:
type(image)

numpy.ndarray

In [64]:
image.size

2359296

In [65]:
image.shape

(768, 1024, 3)

In [66]:
image.dtype

dtype('uint8')

In [67]:
iR = image[:,:,0]
iG = image[:,:,1]
iB = image[:,:,2]

In [68]:
iR.shape

(768, 1024)

In [69]:
misc.imsave('pi_image_R.jpg', iR)

In [70]:
image_mod = np.array([iR, iG, iB]).T

In [71]:
image_mod.shape

(1024, 768, 3)

In [72]:
# Save a black and white version of the image based on the red layer
misc.imsave('pi_image_MOD.jpg', image_mod)

In [73]:
# Create a new image with the red and green colours swapped
image_mod = np.dstack((iG, iR, iB))

In [74]:
image_mod.shape

(768, 1024, 3)

In [75]:
misc.imsave('pi_image_MOD.jpg', image_mod)

In [76]:
image.min(), image.max()

(0, 255)

In [77]:
image[0,0,0]

158

In [78]:
def f(x):
    return x*0.5

In [79]:
f(158)

79.0

In [80]:
image_mod = f(image)

In [81]:
misc.imsave('pi_image_MOD.jpg', image_mod)

In [82]:
image = misc.imread('monalisa.png')

In [83]:
image.shape[0:2], (np.array(image.shape[0:2])*0.5).astype(int)

((765, 618), array([382, 309]))

In [84]:
point=(0.5, 0.5)
radius=0.5
s = image.shape

In [85]:
point = (np.array(point)*np.array(s[:2])).astype(int)
point

array([382, 309])

In [86]:
radius = int(radius*min((s[:2])))
radius

309

In [87]:
size = s[0]*s[1]
size

472770

In [88]:
def spotlight(image, point=(0.5, 0.5), radius=0.5):
    print np.array(image.shape[0:2]), point, radius
    s = image.shape
    point = (np.array(point)*np.array(s[:2])).astype(int)
    radius = int(radius*min((s[:2])))
    print s, point, radius
    n = np.zeros(image.size, dtype=image.dtype).reshape(s)
    for index, i in np.ndenumerate(image):
        n[index] = max(0,int(i*(1 - (np.sqrt((index[0] - point[0])**2 + (index[1] - point[1])**2))/radius)))
    return n

In [89]:
image_mod = spotlight(image)

[765 618] (0.5, 0.5) 0.5
(765, 618, 4) [382 309] 309


In [90]:
print image_mod.shape
print np.min(image_mod), np.max(image_mod)

(765, 618, 4)
0 255


In [91]:
misc.imsave('monalisa_mod.jpg', image_mod)