## Trim Outer Zeros from 2D or 3D Numpy Array

- https://stackoverflow.com/questions/55917328/numpy-trim-zeros-in-2d-or-3d/65547931#65547931
- https://stackoverflow.com/questions/65547529/how-to-remove-surrounding-empty-data-from-3d-array#65547738

In [1]:
import numpy as np

Numpy function [`trim_zeros`](https://numpy.org/doc/stable/reference/generated/numpy.trim_zeros.html) only works on 1-D arrays

In [2]:
help(np.trim_zeros)

Help on function trim_zeros in module numpy:

trim_zeros(filt, trim='fb')
    Trim the leading and/or trailing zeros from a 1-D array or sequence.
    
    Parameters
    ----------
    filt : 1-D array or sequence
        Input array.
    trim : str, optional
        A string with 'f' representing trim from front and 'b' to trim from
        back. Default is 'fb', trim zeros from both front and back of the
        array.
    
    Returns
    -------
    trimmed : 1-D array or sequence
        The result of trimming the input. The input data type is preserved.
    
    Examples
    --------
    >>> a = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
    >>> np.trim_zeros(a)
    array([1, 2, 3, 0, 2, 1])
    
    >>> np.trim_zeros(a, 'b')
    array([0, 0, 0, ..., 0, 2, 1])
    
    The input data type is preserved, list/tuple in means list/tuple out.
    
    >>> np.trim_zeros([0, 1, 2, 0])
    [1, 2]



Example for a 2-D array

In [13]:
# Indices of all nonzero elements
nz = np.nonzero(arr)
nz

(array([1, 2, 2, 2, 3, 3, 4, 4, 4, 5, 5]),
 array([3, 1, 2, 3, 1, 3, 0, 1, 3, 0, 3]))

In [14]:
arr_trimmed = arr[nz[0].min():nz[0].max()+1, nz[1].min():nz[1].max()+1]
arr_trimmed

array([[0, 0, 0, 1],
       [0, 1, 1, 1],
       [0, 1, 0, 1],
       [1, 1, 0, 1],
       [1, 0, 0, 1]])

In [16]:
nz = np.nonzero(arr)
arr_trimmed = arr[nz[0].min():nz[0].max()+1,
                  nz[1].min():nz[1].max()+1]

assert np.array_equal(arr_trimmed, [
    [0, 0, 0, 1],
    [0, 1, 1, 1],
    [0, 1, 0, 1],
    [1, 1, 0, 1],
    [1, 0, 0, 1]
])

This can be generalized to N-dimensions as follows:

In [17]:
def trim_zeros(arr):
    slices = tuple(slice(min(idx), max(idx)+1)
                   for idx in np.nonzero(arr))
    return arr[slices]

test = np.zeros((5,5,5,5))
test[1:3,1:3,1:3,1:3] = 1
trimmed_array = trim_zeros(test)
assert trimmed_array.shape == (2, 2, 2, 2)
assert trimmed_array.sum() == 2**4

In [18]:
assert np.array_equal(trim_zeros(arr), [
    [0, 0, 0, 1],
    [0, 1, 1, 1],
    [0, 1, 0, 1],
    [1, 1, 0, 1],
    [1, 0, 0, 1]
])